(() => {
  const drawer = document.querySelector('#review-drawer');
  const form = document.querySelector('#review-form');
  const threads = document.querySelector('#review-threads');
  const targetLabel = document.querySelector('#review-target');
  let target = null;
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function api(path, options) { const response = await fetch(path, { headers: {'content-type':'application/json'}, ...options }); const value = await response.json(); if (!response.ok) throw new Error(value.error || response.statusText); return value; }
  async function refresh() {
    const all = await api('/api/comments');
    const matching = all.filter((item) => item.target.record_id === target.record_id && (item.target.field || '') === (target.field || '') && (item.target.page || '') === (target.page || ''));
    threads.innerHTML = matching.map((item) => '<article class="live-thread"><span class="tag">' + esc(item.status) + '</span><p>' + esc(item.body) + '</p>' + (item.replies || []).map((reply) => '<p><strong>' + esc(reply.author) + ':</strong> ' + esc(reply.body) + '</p>').join('') + (item.status === 'open' ? '<form class="reply-form" data-reply="' + esc(item.id) + '"><label>Reply <input name="body" required></label><button type="submit">Reply</button></form><button data-agent="' + esc(item.id) + '">Request agent</button><button data-resolve="' + esc(item.id) + '">Resolve</button><div data-job-for="' + esc(item.id) + '"></div>' : '') + '</article>').join('') || '<p>No comments on this target.</p>';
  }
  function open(button) { const host = button.closest('[data-record-id][data-field]'); target = host ? {record_id: host.dataset.recordId, field: host.dataset.field} : {record_id: document.body.dataset.workspaceId, page: button.dataset.pageTarget}; targetLabel.textContent = target.record_id + ' · ' + (target.field || target.page); drawer.showModal(); refresh().catch(showError); }
  function showError(error) { threads.textContent = String(error); }
  document.querySelectorAll('[data-record-id][data-field]').forEach((host) => { if (host.querySelector(':scope > .review-trigger')) return; const button = document.createElement('button'); button.type='button'; button.className='review-trigger'; button.setAttribute('aria-label', 'Comment on ' + host.dataset.recordId + ' ' + host.dataset.field); button.textContent='✎'; host.append(button); });
  document.addEventListener('click', async (event) => { const button = event.target.closest('button'); if (!button) return; if (button.classList.contains('review-trigger')) return open(button); try { if (button.dataset.agent) { const job = await api('/api/comments/' + encodeURIComponent(button.dataset.agent) + '/agent', {method:'POST'}); const slot = document.querySelector('[data-job-for="' + button.dataset.agent + '"]'); slot.textContent='Agent queued…'; const poll = async () => { const current = await api('/api/jobs/' + encodeURIComponent(job.id)); if (current.status === 'queued') return setTimeout(poll, 100); slot.innerHTML = current.status === 'failed' ? esc(current.error) : '<p>' + esc(current.response.message) + '</p>' + (current.response.proposal ? '<pre class="proposal">' + esc(JSON.stringify(current.response.proposal, null, 2)) + '</pre><button data-apply="' + esc(job.id) + '">Apply proposal</button>' : ''); }; poll(); } if (button.dataset.resolve) { await api('/api/comments/' + encodeURIComponent(button.dataset.resolve) + '/resolve', {method:'POST', body:JSON.stringify({resolution:'accepted-no-change'})}); await refresh(); } if (button.dataset.apply) { await api('/api/jobs/' + encodeURIComponent(button.dataset.apply) + '/apply', {method:'POST'}); await refresh(); location.reload(); } } catch (error) { showError(error); } });
  document.addEventListener('submit', async (event) => { const reply = event.target.closest('.reply-form'); if (!reply) return; event.preventDefault(); try { const body = new FormData(reply).get('body'); await api('/api/comments/' + encodeURIComponent(reply.dataset.reply) + '/replies', {method:'POST', body:JSON.stringify({body, author:'browser reviewer'})}); await refresh(); } catch (error) { showError(error); } });
  form.addEventListener('submit', async (event) => { event.preventDefault(); try { const body = new FormData(form).get('body'); await api('/api/comments', {method:'POST', body:JSON.stringify({target, body, author:'browser reviewer'})}); form.reset(); await refresh(); } catch (error) { showError(error); } });
})();
